// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM7KmFowwSrOBGH635ocqiN5MrMSbr1bo',
    appId: '1:739962222655:web:50fe471009bf5ebfba208a',
    messagingSenderId: '739962222655',
    projectId: 'monocle-mtg',
    authDomain: 'monocle-mtg.firebaseapp.com',
    storageBucket: 'monocle-mtg.appspot.com',
    measurementId: 'G-5SBQJWPKVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPR6PY8vq1V0eGqHWD4_9vv1O65-aT7VU',
    appId: '1:739962222655:android:64c6fe8d691461cbba208a',
    messagingSenderId: '739962222655',
    projectId: 'monocle-mtg',
    storageBucket: 'monocle-mtg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDleArNLlSC3JR5Zj_vkpw1OheyHuNFP3A',
    appId: '1:739962222655:ios:015a8fb702d413f7ba208a',
    messagingSenderId: '739962222655',
    projectId: 'monocle-mtg',
    storageBucket: 'monocle-mtg.appspot.com',
    iosClientId: '739962222655-hhcuf7t3ka7na7bvfkon8g09nd5atmad.apps.googleusercontent.com',
    iosBundleId: 'com.volmit.monocle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDleArNLlSC3JR5Zj_vkpw1OheyHuNFP3A',
    appId: '1:739962222655:ios:015a8fb702d413f7ba208a',
    messagingSenderId: '739962222655',
    projectId: 'monocle-mtg',
    storageBucket: 'monocle-mtg.appspot.com',
    iosClientId: '739962222655-hhcuf7t3ka7na7bvfkon8g09nd5atmad.apps.googleusercontent.com',
    iosBundleId: 'com.volmit.monocle',
  );
}
